### ISSUE TITLE
`TypeError: dest.on is not a function` for gulp v3.9.1

### ISSUE THREAD

**Issue by conmute** [shama/webpack-stream#138]
Please see this output

    > gulp wip

    [19:09:30] Requiring external module babel-register
    [19:09:32] Using gulpfile ~/Documents/projects/base/project/client/gulpfile.babel.js
    [19:09:32] Starting 'wip'...
    [19:09:32] 'wip' errored after 37 ms
    [19:09:32] TypeError: dest.on is not a function
        at DestroyableTransform.Readable.pipe (/home/roman/Documents/projects/base/project/client/node_modules/readable-stream/lib/_stream_readable.js:494:8)
        at /home/roman/Documents/projects/base/project/client/gulpfile.babel.js:129:17
        at taskWrapper (/home/roman/Documents/projects/base/project/client/node_modules/undertaker/lib/set-task.js:13:15)
        at bound (domain.js:280:14)
        at runBound (domain.js:293:12)
        at asyncRunner (/home/roman/Documents/projects/base/project/client/node_modules/async-done/index.js:36:18)
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickCallback (internal/process/next_tick.js:98:9)
        at Module.runMain (module.js:606:11)
        at run (bootstrap_node.js:394:7)
        at startup (bootstrap_node.js:149:9)
        at bootstrap_node.js:509:3> gulp wip

    [19:09:30] Requiring external module babel-register
    [19:09:32] Using gulpfile ~/Documents/projects/base/project/client/gulpfile.babel.js
    [19:09:32] Starting 'wip'...
    [19:09:32] 'wip' errored after 37 ms
    [19:09:32] TypeError: dest.on is not a function
        at DestroyableTransform.Readable.pipe (/home/roman/Documents/projects/base/project/client/node_modules/readable-stream/lib/_stream_readable.js:494:8)
        at /home/roman/Documents/projects/base/project/client/gulpfile.babel.js:129:17
        at taskWrapper (/home/roman/Documents/projects/base/project/client/node_modules/undertaker/lib/set-task.js:13:15)
        at bound (domain.js:280:14)
        at runBound (domain.js:293:12)
        at asyncRunner (/home/roman/Documents/projects/base/project/client/node_modules/async-done/index.js:36:18)
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickCallback (internal/process/next_tick.js:98:9)
        at Module.runMain (module.js:606:11)
        at run (bootstrap_node.js:394:7)
        at startup (bootstrap_node.js:149:9)
        at bootstrap_node.js:509:3

The code is just exact as in examples:

    gulp.task("wip", () => {

        return gulp.src(destination.client + "client.js")
                .pipe(webpack({}))
                .pipe(gulp.dest(destination.client + "/webpack"));

    });

yet it seems to work ok after update gulp to v4.

**Comment by itsmelion** [comment]
Is there a Gulp v4? You mean `webpack-stream` v4 right?

i have 
```"gulp": "^3.9.1",
"webpack-stream": "^4.0.0"```
and still, i get this error.

**Comment by itsmelion** [comment]
Nevermind.
The point is that i imported webpack-stream with a different name.

i declared on my `gulpconfig.js` file `const gulpWebpack = require('webpack-stream');` but on the function i was calling `.pipe( webpack() );` .. changing to `.pipe( gulpWebpack() );` now works fine for me

**Comment by geosenna** [comment]
I have the same issue with this code:

```
export const prodJS = () =>
    gulp
        .src(PATHS.SRC.js)
        .pipe(webpackConfig.plugins.push(
            new UglifyJsPlugin()
        ))
        .pipe(webpackStream(webpackConfig), webpack)
        .pipe(header(banner, { pkg: pkg, now: now }))
        .pipe(rename({ suffix: '.min' }))
        .pipe(gulp.dest(PATHS.DEST.js))
```

When I remove this line, it is working fine;
```
        .pipe(webpackConfig.plugins.push(
            new UglifyJsPlugin()
        ))

```

**Comment by shama** [comment]
Looking at the stack trace, I don't see how this is related to this library. If I am wrong, please provide the path to the problematic portion of code in this library. Thanks!
