### ISSUE TITLE
Concurrent Compilation Error

### ISSUE THREAD

**Issue by tleef** [shama/webpack-stream#201]
Caching the webpack compiler, introduced in PR #109, causes an error when compiling multiple files concurrently.

This issue is not related to gulp however I ran into it when using gulp to compile my project. I am working with a mono-repo where I have a `services` directory which contains several microservices. each microservice has its own `src` directory which contains an `index.js`.

I use the following code to compile each micro service individually

```
gulp.task('webpack', function () {
  const tasks = getDirectories(`./services`).map((dir) => {
    return gulp.src(join(dir, 'src/index.js'))
      .pipe(webpack(require('./webpack.config.js'), compiler))
      .pipe(gulp.dest(join(dir, 'dist/')))
  })

  return merge(tasks)
})
```
webpack-stream 5.0.0 works as expected and produces a compiled version of each microservice which is stored in a `dist` directory alongside its respective `src` directory.

webpack-stream 5.1.0 introduced caching and reuses the same webpack instance for each compilation task which results in the following error:

```
ConcurrentCompilationError: You ran Webpack twice. Each instance only supports a single concurrent compilation at a time.
```

**Comment by bobbybol** [comment]
I'm having the exact same issue when going from 5.0.0 to 5.1.0 - hoping for a fix or instructions on how to have multiple compilations.

**Comment by WillsB3** [comment]
I'm also seeing this issue when using `webpack-stream` in combination with `gulp.parallel`.

**Comment by Renkas** [comment]
Any update on a fix?

**Comment by shama** [comment]
Patches are welcome.

**Comment by mightydes** [comment]
+1

**Comment by An-Haijun** [comment]
> I came across the same error and fixed it by downgrading to `5.0`, but it would be nice to have the cache working correctly/reliably.

Thanks, it helped me.

**Comment by An-Haijun** [comment]
> I came across the same error and fixed it by downgrading to `5.0`, but it would be nice to have the cache working correctly/reliably.

@danieldiekmeier Thanks, it helped me

**Comment by Drafteed** [comment]
#207 increased rebuild time up to 52x (!) for my project. [See this](https://github.com/shama/webpack-stream/issues/237#issuecomment-933597315).
